// import { sign } from "crypto";
import { signInWithGooglePopup,signInWithGoogleRedirect,createUserDocumentFromAuth } from "../../utils/firebase/firebase.utils";
import SignUpForm from "../../components/sign-up-form/sign-up-form.component";
import "./sign.scss"
import Button from "../../components/button/button.component";
const Signin=()=>{
    const logGoogleUser = async ()=>{
        //response will get access to object being generated by signin
        const {user} = await signInWithGooglePopup();
        //we have destrucutured the object from response as response.user now we are getting response.user
        createUserDocumentFromAuth(user);
    };

    return (
        <div className="container">
    <h1>Sign In</h1>
    <button onClick={logGoogleUser}>SIGN IN</button>
    <button onClick={logGoogleUser}buttonType="google">Sign In With Google</button>
    <div className="sign">
    <SignUpForm className="sign"/>
        </div>
        </div>
    )
}
export default Signin;