// import { sign } from "crypto";
import { signInWithGooglePopup,createUserDocumentFromAuth } from "../../utils/firebase/firebase.utils";
const Signin=()=>{
    const logGoogleUser = async ()=>{
        //response will get access to object being generated by signin
        const {user} = await signInWithGooglePopup();
        //we have destrucutured the object from response as response.user now we are getting response.user
        createUserDocumentFromAuth(user);
    }
    return (
        <div>
    <h1>Sign In</h1>;
    <button onClick={logGoogleUser}>Sign In With Google</button>
        </div>
    )
}
export default Signin;